const STATUS = {
  NOT_CHECKED: 'NOT_CHECKED',
  CHECKING: 'CHECKING',
  READY: 'READY',
  MISSING: 'MISSING',
  INSTALLING: 'INSTALLING',
  INSTALLED: 'INSTALLED',
  VERIFYING: 'VERIFYING',
  FAILED: 'FAILED',
  WARNING: 'WARNING',
  BYPASSED: 'BYPASSED',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
  BLOCKED: 'BLOCKED'
};

const SEVERITY = {
  HARD_BLOCKER: 'HARD_BLOCKER', // Cannot perform requested capability
  SOFT_REQUIREMENT: 'SOFT_REQUIREMENT', // Alternate provider exists
  OPTIONAL: 'OPTIONAL' // Quality enhancement
};

const CATEGORIES = {
  ENVIRONMENT: 'Environment',
  HARDWARE: 'Hardware',
  DEPENDENCY: 'Dependency',
  MODEL_RUNTIME: 'Model Runtime',
  PROVIDER: 'Provider',
  STORAGE: 'Storage',
  CREDENTIAL: 'Credential'
};

const CAPABILITIES = {
  TEXT_GENERATION: 'TEXT_GENERATION',
  NARRATION: 'NARRATION',
  IMAGE_GENERATION: 'IMAGE_GENERATION',
  VIDEO_GENERATION: 'VIDEO_GENERATION',
  CAPTION_GENERATION: 'CAPTION_GENERATION',
  VIDEO_ASSEMBLY: 'VIDEO_ASSEMBLY',
  THUMBNAIL_GENERATION: 'THUMBNAIL_GENERATION',
  SEO_GENERATION: 'SEO_GENERATION',
  EXPORT: 'EXPORT'
};

module.exports = { STATUS, SEVERITY, CATEGORIES, CAPABILITIES };
